-- ============================================================================
--  SaaS Churn Analysis - SQL Layer
--  Capstone project, internship portfolio piece
--
--  ALL DATA IN THIS PROJECT IS SYNTHETIC AND SIMULATED.
--  It is generated by data/generate_dataset.py and does not describe any real
--  company, customer, or revenue.
--
--  Purpose
--  -------
--  This script reproduces the same answers as python/data_analysis.py using
--  SQL only. It is written for DuckDB, which reads the CSV files directly with
--  read_csv_auto(), so no database server or import step is required.
--
--  How to run
--  -----------
--      pip install duckdb
--      duckdb < sql/analysis.sql
--  or, from Python:
--      import duckdb; duckdb.connect().execute(open("sql/analysis.sql").read())
--
--  Notes on approach
--  -----------------
--  * The raw tables are messy on purpose (duplicates, mixed date formats,
--    text numbers, missing values). Section 1 rebuilds a clean layer with CTEs
--    so every later query can rely on it.
--  * Both raw files are read with all_varchar=true. Letting the reader infer
--    types would hand us a DATE where the column actually holds a mix of
--    spellings, and then TRIM() fails. Reading everything as text and casting
--    explicitly is the honest way to clean a messy file.
--  * Retention uses a survival-style definition: a customer is "at risk" in
--    month t only if they survived past t. Customers still active at the end
--    of the data are censored - they count as at risk, but not as churn.
--    This is what stops the retention curve from collapsing at the end of the
--    period, which is the single most common mistake in churn analysis.
--  * Findings are reported as associations, not causes.
--  * Text labels come out UPPER-CASED here, while the Python layer title-cases
--    them. The numbers are identical; only the display casing differs.
--
--  Verification
--  ------------
--  python/validate_sql.py runs this file and compares its output with the CSVs
--  from data_analysis.py, measure by measure. Run it after any change here.
-- ============================================================================


-- ============================================================================
--  SECTION 1  |  CLEANING LAYER
--  Rebuilds the two clean tables that python/data_analysis.py produces.
-- ============================================================================

CREATE OR REPLACE VIEW v_customers_clean AS
WITH dedup AS (
    -- The raw file contains deliberate duplicate rows.
    SELECT * EXCLUDE (rn)
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY signup_date) AS rn
        FROM read_csv_auto('data/raw/customers_raw.csv', header = true,
                           all_varchar = true)
    )
    WHERE rn = 1
),
typed AS (
    SELECT
        customer_id,
        -- Two spellings appear: '2024-10-01' and '01/08/2023' (day first).
        -- try_cast handles the ISO rows; the slash rows are handled below.
        TRY_CAST(NULLIF(TRIM(signup_date), '') AS DATE)                AS signup_date,
        UPPER(TRIM(plan_tier))                                          AS plan_tier,
        UPPER(TRIM(industry))                                           AS industry,
        UPPER(TRIM(country))                                            AS country,
        -- 'EMEA' and 'Europe' are the same region; normalise to one label.
        CASE WHEN UPPER(TRIM(region)) IN ('EMEA', 'EUROPE') THEN 'Europe'
             ELSE UPPER(TRIM(region)) END                              AS region,
        UPPER(TRIM(company_size))                                       AS company_size,
        TRY_CAST(NULLIF(TRIM(seats), '') AS INTEGER)                   AS seats,
        UPPER(TRIM(billing_cycle))                                      AS billing_cycle,
        UPPER(TRIM(acquisition_channel))                                AS acquisition_channel,
        TRY_CAST(NULLIF(TRIM(discount_pct), '') AS DOUBLE)             AS discount_pct,
        -- mrr_at_signup is sometimes text like "$1,250.00".
        TRY_CAST(
            REPLACE(REPLACE(NULLIF(TRIM(mrr_at_signup), ''), '$', ''), ',', '')
            AS DOUBLE)                                                  AS mrr_at_signup,
        UPPER(TRIM(status))                                             AS status,
        -- The slash-formatted dates are day first, so strptime is told so
        -- explicitly. Guessing here silently turns 1 August into 8 January.
        COALESCE(
            TRY_CAST(NULLIF(TRIM(churn_date), '') AS DATE),
            TRY_STRPTIME(NULLIF(TRIM(churn_date), ''), '%d/%m/%Y')::DATE
        )                                                               AS churn_date,
        NULLIF(TRIM(churn_reason), '')                                  AS churn_reason,
        TRY_CAST(NULLIF(TRIM(tenure_months), '') AS INTEGER)           AS tenure_months,
        TRY_CAST(NULLIF(TRIM(nps_score), '') AS DOUBLE)                 AS nps_score,
        TRY_CAST(NULLIF(TRIM(last_login_date), '') AS TIMESTAMP)        AS last_login_date,
        TRY_CAST(NULLIF(TRIM(seats_current), '') AS INTEGER)            AS seats_current
    FROM dedup
),
cleaned AS (
    -- EXCLUDE is used instead of a bare * because these two columns are being
    -- replaced by corrected versions. Writing "* , <expr> AS mrr_at_signup"
    -- would not overwrite anything: DuckDB keeps the original and renames the
    -- new one to mrr_at_signup_1, so every later reference would silently use
    -- the UNCORRECTED value.
    SELECT * EXCLUDE (mrr_at_signup, churn_date),
        -- A negative MRR is a data-entry error, not a discount.
        CASE WHEN mrr_at_signup < 0 THEN NULL ELSE mrr_at_signup END    AS mrr_at_signup,
        CASE WHEN churn_date < signup_date THEN NULL ELSE churn_date END AS churn_date,
        -- status was upper-cased in the previous CTE, so compare against
        -- 'CHURNED'. Comparing to 'Churned' here would never match and would
        -- report zero churn everywhere.
        CASE WHEN status = 'CHURNED' THEN 1 ELSE 0 END                  AS churn_flag,
        DATE_TRUNC('month', signup_date)                                AS signup_cohort
    FROM typed
)
-- One last integrity check, mirroring the Python pipeline: every churned
-- customer must have a churn date, and no active customer may have one.
SELECT
    *,
    mrr_at_signup * 12                                     AS arr,
    mrr_at_signup / NULLIF(seat_estimate, 0)               AS arpu,
    mrr_at_signup * tenure_months                          AS lifetime_value,
    CASE
        WHEN mrr_at_signup <= 200  THEN 'Starter'
        WHEN mrr_at_signup <= 800  THEN 'Growth'
        WHEN mrr_at_signup <= 2000 THEN 'Business'
        ELSE 'Enterprise'
    END                                                   AS plan_band_by_mrr
FROM (
    SELECT *,
           -- Seat counts are missing for some rows; fall back to an estimate
           -- derived from MRR so seat-based analysis stays complete.
           COALESCE(seats, mrr_at_signup / 40)             AS seat_estimate
    FROM cleaned
);


CREATE OR REPLACE VIEW v_monthly_clean AS
WITH dedup AS (
    SELECT * EXCLUDE (rn)
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                   PARTITION BY customer_id, month_start ORDER BY month_start
               ) AS rn
        FROM read_csv_auto('data/raw/customer_monthly_raw.csv', header = true,
                           all_varchar = true)
    )
    WHERE rn = 1
)
SELECT
    customer_id,
    TRY_CAST(month_start AS DATE)      AS month_start,
    TRY_CAST(month_number AS INTEGER)  AS month_number,
    TRY_CAST(year AS INTEGER)          AS year,
    TRY_CAST(tenure_month AS INTEGER)  AS tenure_month,
    TRY_CAST(mrr AS DOUBLE)            AS mrr,
    TRY_CAST(seats AS INTEGER)         AS seats,
    TRY_CAST(active_users AS INTEGER)  AS active_users,
    -- adoption_rate is stored on a 0-1 scale for some rows and 0-100 for
    -- others. Anything above 1 is a percentage and gets rescaled.
    CASE
        WHEN TRY_CAST(adoption_rate AS DOUBLE) > 1
            THEN TRY_CAST(adoption_rate AS DOUBLE) / 100
        ELSE TRY_CAST(adoption_rate AS DOUBLE)
    END                                AS adoption_rate,
    TRY_CAST(support_tickets AS INTEGER) AS support_tickets,
    TRY_CAST(nps_score AS DOUBLE)      AS nps_score,
    TRY_CAST(is_active AS INTEGER)     AS is_active
FROM dedup
WHERE TRY_CAST(month_start AS DATE) IS NOT NULL;


-- ============================================================================
--  SECTION 2  |  HEADLINE KPIs
--  Answers: what is the state of the business, and how healthy is it?
-- ============================================================================

SELECT '--- Headline KPIs ---' AS section;

WITH latest AS (SELECT MAX(month_start) AS m FROM v_monthly_clean)
SELECT
    (SELECT COUNT(*) FROM v_customers_clean)                        AS total_customers,
    (SELECT COUNT(*) FROM v_customers_clean WHERE churn_flag = 1)   AS churned_customers,
    (SELECT COUNT(*) FROM v_customers_clean WHERE churn_flag = 0)   AS active_customers,
    ROUND(100.0 * SUM(churn_flag) / COUNT(*), 1)                    AS logo_churn_rate_pct,
    (SELECT ROUND(SUM(mrr)) FROM v_monthly_clean, latest)           AS mrr_latest_month,
    (SELECT ROUND(SUM(mrr) * 12) FROM v_monthly_clean, latest)      AS arr_run_rate,
    (SELECT ROUND(SUM(mrr) / COUNT(DISTINCT customer_id))
       FROM v_monthly_clean, latest)                                AS arpu,
    (SELECT ROUND(AVG(nps_score), 2) FROM v_customers_clean)         AS avg_nps,
    (SELECT ROUND(AVG(tenure_months), 1) FROM v_customers_clean)    AS avg_tenure_months
FROM v_customers_clean;


-- ============================================================================
--  SECTION 3  |  MONTHLY TREND
--  Answers: is the business growing or shrinking?
--  New customers come from the master table; cancellations are counted from
--  the churn date. Both are bucketed to the same calendar month.
-- ============================================================================

SELECT '--- Monthly trend ---' AS section;

WITH signups AS (
    SELECT signup_cohort AS month_start, COUNT(*) AS new_customers
    FROM v_customers_clean
    GROUP BY 1
),
cancellations AS (
    SELECT DATE_TRUNC('month', churn_date) AS month_start,
           COUNT(*) AS churned_customers
    FROM v_customers_clean
    WHERE churn_flag = 1
    GROUP BY 1
)
SELECT
    m.month_start,
    ROUND(SUM(m.mrr))                                   AS total_mrr,
    COUNT(DISTINCT m.customer_id)                       AS active_customers,
    COALESCE(s.new_customers, 0)                        AS new_customers,
    COALESCE(c.churned_customers, 0)                    AS churned_customers,
    COALESCE(s.new_customers, 0) - COALESCE(c.churned_customers, 0) AS net_new_customers,
    ROUND(100.0 * SUM(m.mrr)
          / LAG(SUM(m.mrr)) OVER (ORDER BY m.month_start) - 100, 2) AS mom_growth_pct
FROM v_monthly_clean m
LEFT JOIN signups s        ON s.month_start = m.month_start
LEFT JOIN cancellations c  ON c.month_start = m.month_start
GROUP BY 1, 4, 5
ORDER BY 1;


-- ============================================================================
--  SECTION 4  |  RETENTION SURVIVAL CURVE
--  Answers: when do customers leave?
--
--  at_risk(t) = customers who were still subscribed AFTER month t.
--  This is a survival calculation, not a raw share of the base. Dividing
--  cancellations by everyone who ever signed up would make the curve plunge
--  to zero at the end of the period purely because the data stops there.
-- ============================================================================

SELECT '--- Retention by tenure (survival) ---' AS section;

WITH base AS (
    SELECT
        c.customer_id,
        -- The monthly table counts tenure from 0, while the master table counts
        -- it from 1 (a customer in their first month has tenure_months = 1).
        -- Adding 1 puts both on the same footing; mixing the two conventions
        -- shifts the whole survival curve by one month.
        MAX(m.tenure_month) + 1 AS tenure_reached,
        (c.churn_flag = 1)      AS churned
    FROM v_customers_clean c
    JOIN v_monthly_clean m USING (customer_id)
    GROUP BY 1, 3
),
grid AS (SELECT UNNEST(GENERATE_SERIES(0, 23)) AS t),
risk AS (
    SELECT
        g.t,
        -- Still subscribed after month t.
        COUNT(*) FILTER (WHERE b.tenure_reached > g.t)  AS at_risk,
        -- Churned exactly at month t. Active-at-end customers are censored
        -- and deliberately excluded here.
        COUNT(*) FILTER (WHERE b.tenure_reached = g.t + 1 AND b.churned) AS cancellations
    FROM grid g
    CROSS JOIN base b
    GROUP BY 1
)
SELECT
    t                                            AS tenure_month,
    at_risk,
    cancellations,
    ROUND(100.0 * cancellations / NULLIF(at_risk, 0), 2) AS monthly_churn_pct,
    ROUND(100.0 * (1 - cancellations / NULLIF(at_risk, 0)), 2) AS retention_pct
FROM risk
WHERE at_risk > 0
ORDER BY t;


-- ============================================================================
--  SECTION 5  |  COHORT RETENTION
--  Answers: do newer customers stick around as well as older ones?
--
--  Each average uses ONLY the cohorts that lived long enough to reach the
--  month in question. Averaging in younger cohorts as 0% would understate
--  retention badly - a cohort that signed up last month has not "failed" yet.
-- ============================================================================

SELECT '--- Cohort retention ---' AS section;

WITH cohort_sizes AS (
    SELECT signup_cohort, COUNT(*) AS cohort_size
    FROM v_customers_clean
    GROUP BY 1
),
survived AS (
    SELECT
        c.signup_cohort,
        m.tenure_month,
        COUNT(DISTINCT m.customer_id) AS still_subscribed
    FROM v_customers_clean c
    JOIN v_monthly_clean m USING (customer_id)
    GROUP BY 1, 2
),
reach AS (
    -- Longest tenure each cohort actually reached, i.e. how far it can be read.
    SELECT signup_cohort, MAX(tenure_month) AS max_tenure_reached
    FROM survived
    GROUP BY 1
),
grid AS (SELECT UNNEST(GENERATE_SERIES(0, 23)) AS t),
cohort_grid AS (
    SELECT r.signup_cohort, r.max_tenure_reached, g.t
    FROM reach r CROSS JOIN grid g
)
SELECT
    cg.signup_cohort                                        AS cohort,
    cs.cohort_size,
    cg.t                                                    AS tenure_month,
    COALESCE(s.still_subscribed, 0)                         AS still_subscribed,
    ROUND(100.0 * COALESCE(s.still_subscribed, 0) / cs.cohort_size, 1) AS retention_pct,
    -- FALSE where the cohort has not yet reached this month of tenure.
    cg.t <= cg.max_tenure_reached                           AS is_observable
FROM cohort_grid cg
JOIN cohort_sizes cs USING (signup_cohort)
LEFT JOIN survived s
       ON s.signup_cohort = cg.signup_cohort AND s.tenure_month = cg.t
ORDER BY cg.signup_cohort, cg.t;


--  Readable summary: average retention at key months, eligible cohorts only.
SELECT '--- Average retention, eligible cohorts only ---' AS section;

WITH cohort_sizes AS (
    SELECT signup_cohort, COUNT(*) AS cohort_size FROM v_customers_clean GROUP BY 1
),
survived AS (
    SELECT c.signup_cohort, m.tenure_month, COUNT(DISTINCT m.customer_id) AS n
    FROM v_customers_clean c JOIN v_monthly_clean m USING (customer_id)
    GROUP BY 1, 2
),
reach AS (
    SELECT signup_cohort, MAX(tenure_month) AS max_tenure_reached
    FROM survived GROUP BY 1
),
joined AS (
    SELECT s.signup_cohort, s.tenure_month, s.n, cs.cohort_size, r.max_tenure_reached
    FROM survived s
    JOIN cohort_sizes cs USING (signup_cohort)
    JOIN reach r USING (signup_cohort)
)
SELECT
    tenure_month,
    COUNT(*) AS cohorts_eligible,
    ROUND(AVG(100.0 * n / cohort_size), 1) AS avg_retention_pct
FROM joined
WHERE tenure_month <= max_tenure_reached
  AND tenure_month IN (1, 3, 6, 12, 18)
GROUP BY 1
ORDER BY 1;


-- ============================================================================
--  SECTION 6  |  CHURN BY SEGMENT
--  Answers: which customers are we losing?
--
--  Two different questions are answered here and they give different answers:
--    churn_pct         - which segment loses the most LOGOS
--    share_of_losses   - which segment costs the most REVENUE
--  Chasing the wrong one is the usual mistake: the segment with the highest
--  churn rate is rarely the segment with the largest revenue impact.
-- ============================================================================

SELECT '--- Churn and revenue impact by plan tier ---' AS section;

WITH base AS (
    SELECT plan_tier, churn_flag, mrr_at_signup FROM v_customers_clean
)
SELECT
    plan_tier,
    COUNT(*)                                            AS customers,
    SUM(churn_flag)                                      AS churned,
    ROUND(100.0 * SUM(churn_flag) / COUNT(*), 1)         AS churn_pct,
    ROUND(SUM(mrr_at_signup))                            AS total_mrr,
    ROUND(SUM(mrr_at_signup * churn_flag))               AS mrr_lost,
    ROUND(100.0 * SUM(mrr_at_signup * churn_flag)
          / SUM(SUM(mrr_at_signup * churn_flag)) OVER (), 1) AS share_of_all_losses_pct
FROM base
GROUP BY 1
ORDER BY churn_pct DESC;


SELECT '--- Churn by acquisition channel, with deal quality ---' AS section;

WITH base AS (
    SELECT
        acquisition_channel,
        churn_flag,
        mrr_at_signup,
        discount_pct,
        mrr_at_signup * tenure_months AS lifetime_value
    FROM v_customers_clean
)
SELECT
    acquisition_channel,
    COUNT(*)                                            AS customers,
    SUM(churn_flag)                                      AS churned,
    ROUND(100.0 * SUM(churn_flag) / COUNT(*), 1)         AS churn_pct,
    ROUND(AVG(discount_pct), 1)                          AS avg_discount_pct,
    ROUND(AVG(mrr_at_signup))                            AS avg_mrr,
    ROUND(AVG(lifetime_value))                           AS avg_lifetime_value,
    -- Rank 1 = highest churn. Rank 1 = lowest LTV means the worst channel on
    -- both measures, which is the one to cut spend on.
    RANK() OVER (ORDER BY 100.0 * SUM(churn_flag) / COUNT(*) DESC) AS churn_rank,
    RANK() OVER (ORDER BY AVG(lifetime_value))                     AS ltv_rank
FROM base
GROUP BY 1
ORDER BY churn_pct DESC;


-- ============================================================================
--  SECTION 7  |  EARLY WARNING SIGNALS
--  Answers: is there anything measurable before a customer cancels?
--
--  Compares the final 3 months of activity for churned customers against the
--  same window for customers who stayed. These are associations: low adoption
--  may be a symptom of a customer who was already leaving, not the cause.
-- ============================================================================

SELECT '--- Behaviour in the final 3 months: churned vs active ---' AS section;

WITH final_window AS (
    SELECT
        c.customer_id,
        c.churn_flag,
        AVG(m.adoption_rate)     AS avg_adoption,
        AVG(m.support_tickets)   AS avg_tickets,
        AVG(m.nps_score)         AS avg_nps,
        AVG(m.seats)             AS avg_seats
    FROM v_customers_clean c
    JOIN v_monthly_clean m USING (customer_id)
    -- The last 3 months each customer was actually subscribed for.
    WHERE m.tenure_month >= c.tenure_months - 3
    GROUP BY 1, 2
)
SELECT
    ROUND(100.0 * AVG(avg_adoption) FILTER (WHERE f.churn_flag = 1), 1) AS churned_adoption_pct,
    ROUND(100.0 * AVG(avg_adoption) FILTER (WHERE f.churn_flag = 0), 1) AS active_adoption_pct,
    ROUND(AVG(avg_tickets) FILTER (WHERE f.churn_flag = 1), 2)          AS churned_tickets,
    ROUND(AVG(avg_tickets) FILTER (WHERE f.churn_flag = 0), 2)          AS active_tickets,
    ROUND(AVG(avg_nps) FILTER (WHERE f.churn_flag = 1), 2)              AS churned_nps,
    ROUND(AVG(avg_nps) FILTER (WHERE f.churn_flag = 0), 2)              AS active_nps,
    ROUND(AVG(c.discount_pct) FILTER (WHERE f.churn_flag = 1), 1)       AS churned_discount,
    ROUND(AVG(c.discount_pct) FILTER (WHERE f.churn_flag = 0), 1)       AS active_discount
FROM final_window f
JOIN v_customers_clean c USING (customer_id);


-- ============================================================================
--  SECTION 8  |  NET REVENUE RETENTION
--  Answers: is revenue retained from the existing customer base?
--
--  NRR compares the same cohort of customers a year apart, so it is not
--  affected by how many new customers were acquired in between.
--
--  The starting cohort is everyone active in Dec 2023, and the LEFT JOIN is
--  deliberate: a customer who churned during 2024 is still part of the cohort
--  we started with, and contributes 0 to the ending figure. An INNER JOIN would
--  quietly delete them from the denominator, which hides the churn entirely and
--  inflates NRR. (On this data an inner join reports 108% instead of 90%.)
-- ============================================================================

SELECT '--- Net Revenue Retention (Dec 2023 vs Dec 2024) ---' AS section;

CREATE OR REPLACE VIEW v_nrr AS
WITH dec23 AS (
    SELECT customer_id, SUM(mrr) AS mrr_dec23
    FROM v_monthly_clean
    WHERE month_start = DATE '2023-12-01'
    GROUP BY 1
),
dec24 AS (
    SELECT customer_id, SUM(mrr) AS mrr_dec24
    FROM v_monthly_clean
    WHERE month_start = DATE '2024-12-01'
    GROUP BY 1
)
SELECT
    ROUND(SUM(d23.mrr_dec23))                                            AS mrr_12_months_ago,
    ROUND(SUM(COALESCE(d24.mrr_dec24, 0)))                               AS mrr_now_from_retained,
    ROUND(100.0 * SUM(COALESCE(d24.mrr_dec24, 0)) / SUM(d23.mrr_dec23), 1)
                                                                       AS nrr_pct
FROM dec23 d23
LEFT JOIN dec24 d24 USING (customer_id);

SELECT * FROM v_nrr;


-- ============================================================================
--  SECTION 9  |  REVENUE AT RISK
--  Answers: how much recurring revenue sits with accounts that look likely
--  to leave? This is the number a retention campaign is measured against.
--
--  The score is deliberately rule-based rather than a black-box model, so a
--  customer-success manager can see exactly why an account was flagged.
--  Each signal is rescaled to 0-1 so no measurement dominates through its
--  units alone, and the SIGN of the weight carries the direction:
--  negative = a high value is protective, positive = a high value is a warning.
--
--  Rescaling uses the 5th and 95th percentile with clipping, not MIN and MAX,
--  so a handful of extreme Enterprise accounts cannot flatten the score for
--  everyone else. This matches python/data_analysis.py exactly; using MIN/MAX
--  here produces the same account counts and the same correctly-ordered bands,
--  but a visibly different MRR split, which is why validate_sql.py compares
--  the bands rather than just counting them.
-- ============================================================================

-- One row per active account, with its score and band. Exposed as a view so
-- validate_sql.py can read it instead of re-deriving the formula (which is how
-- the two implementations drifted apart in the first place).
CREATE OR REPLACE VIEW v_risk_bands AS
WITH final_month_behaviour AS (
    -- Each customer's own final 3 active months. The window is relative to the
    -- customer, not a fixed month number, so newer accounts are not excluded.
    -- All four measures are MEANS over those 3 months, including final_mrr -
    -- "the average MRR this account was running at just before the analysis
    -- date", which is what python/data_analysis.py computes and what the
    -- column comment there documents. Taking the last month's value instead
    -- (e.g. ARG_MAX) shifts 515 of 820 accounts and quietly changes the MRR
    -- split across bands.
    SELECT
        m.customer_id,
        AVG(m.adoption_rate)       AS final_adoption,
        AVG(m.support_tickets)     AS final_tickets,
        AVG(m.nps_score)           AS final_nps,
        AVG(m.mrr)                 AS final_mrr
    FROM v_monthly_clean m
    JOIN v_customers_clean c2 USING (customer_id)
    WHERE m.tenure_month >= c2.tenure_months - 3
    GROUP BY 1
),
bounds AS (
    -- 5th / 95th percentile of each signal across the active base.
    -- DISTINCT is required, not decorative: a window function without GROUP BY
    -- returns one row per input row, and the CROSS JOIN below would then fan
    -- the active base out against itself (820 x 820 rows).
    SELECT DISTINCT
        QUANTILE_CONT(f.final_adoption, 0.05) OVER () AS adoption_lo,
        QUANTILE_CONT(f.final_adoption, 0.95) OVER () AS adoption_hi,
        QUANTILE_CONT(f.final_tickets,   0.05) OVER () AS tickets_lo,
        QUANTILE_CONT(f.final_tickets,   0.95) OVER () AS tickets_hi,
        QUANTILE_CONT(f.final_nps,       0.05) OVER () AS nps_lo,
        QUANTILE_CONT(f.final_nps,       0.95) OVER () AS nps_hi,
        QUANTILE_CONT(c.tenure_months,   0.05) OVER () AS tenure_lo,
        QUANTILE_CONT(c.tenure_months,   0.95) OVER () AS tenure_hi,
        QUANTILE_CONT(c.discount_pct,    0.05) OVER () AS discount_lo,
        QUANTILE_CONT(c.discount_pct,    0.95) OVER () AS discount_hi,
        QUANTILE_CONT(f.final_mrr,       0.05) OVER () AS mrr_lo,
        QUANTILE_CONT(f.final_mrr,       0.95) OVER () AS mrr_hi
    FROM final_month_behaviour f
    JOIN v_customers_clean c USING (customer_id)
    WHERE c.churn_flag = 0
),
scored AS (
    SELECT
        c.customer_id,
        c.plan_tier,
        c.region,
        c.acquisition_channel,
        c.tenure_months,
        c.mrr_at_signup,
        f.final_mrr,
        f.final_adoption,
        f.final_tickets,
        f.final_nps,
        c.discount_pct,
        -- Rescale to 0-1, clipping to the percentile bounds. The signals are
        -- NOT inverted: the sign of the weight carries the direction, so a
        -- protective signal is weighted negatively rather than flipped to
        -- "1 - x" and then negated again. Inverting here as well would cancel
        -- the weight out and silently reverse the model.
        (GREATEST(LEAST(f.final_adoption, b.adoption_hi), b.adoption_lo) - b.adoption_lo)
            / NULLIF(b.adoption_hi - b.adoption_lo, 0) AS adoption_scaled,
        (GREATEST(LEAST(f.final_tickets, b.tickets_hi), b.tickets_lo) - b.tickets_lo)
            / NULLIF(b.tickets_hi - b.tickets_lo, 0)   AS tickets_scaled,
        (GREATEST(LEAST(f.final_nps, b.nps_hi), b.nps_lo) - b.nps_lo)
            / NULLIF(b.nps_hi - b.nps_lo, 0)           AS nps_scaled,
        (GREATEST(LEAST(c.tenure_months, b.tenure_hi), b.tenure_lo) - b.tenure_lo)
            / NULLIF(b.tenure_hi - b.tenure_lo, 0)     AS tenure_scaled,
        (GREATEST(LEAST(c.discount_pct, b.discount_hi), b.discount_lo) - b.discount_lo)
            / NULLIF(b.discount_hi - b.discount_lo, 0) AS discount_scaled,
        (GREATEST(LEAST(f.final_mrr, b.mrr_hi), b.mrr_lo) - b.mrr_lo)
            / NULLIF(b.mrr_hi - b.mrr_lo, 0)           AS mrr_scaled
    FROM v_customers_clean c
    JOIN final_month_behaviour f USING (customer_id)
    CROSS JOIN bounds b
    WHERE c.churn_flag = 0          -- only accounts that are still active
),
weighted AS (
    SELECT *,
        -2.0 * adoption_scaled     -- low seat use is a warning
        + 1.0 * tickets_scaled     -- more tickets is a warning
        -1.2 * nps_scaled         -- low NPS is a warning
        - 0.8 * tenure_scaled      -- short tenure is a warning
        + 0.6 * discount_scaled    -- heavy discount is a warning
        + 1.0 * mrr_scaled         -- $ at stake
        AS risk_score
    FROM scored
),
banded AS (
    SELECT *, NTILE(3) OVER (ORDER BY risk_score) AS risk_band_id
    FROM weighted
)
SELECT
    customer_id, plan_tier, region, acquisition_channel, tenure_months,
    mrr_at_signup, final_mrr, final_adoption, final_tickets, final_nps,
    discount_pct, risk_score, risk_band_id,
    CASE risk_band_id WHEN 1 THEN 'Low risk' WHEN 2 THEN 'Medium risk'
                      ELSE 'High risk' END AS risk_band
FROM banded;


SELECT '--- Revenue at risk, by risk band ---' AS section;

SELECT
    risk_band,
    COUNT(*)                                                          AS customers,
    ROUND(SUM(final_mrr))                                             AS total_mrr,
    ROUND(100.0 * SUM(final_mrr) / SUM(SUM(final_mrr)) OVER (), 1)     AS share_of_active_mrr_pct,
    ROUND(AVG(risk_score), 3)                                         AS avg_score,
    ROUND(AVG(final_adoption), 3)                                     AS avg_adoption,
    ROUND(AVG(final_nps), 2)                                          AS avg_nps,
    ROUND(AVG(final_tickets), 2)                                      AS avg_tickets
FROM v_risk_bands
GROUP BY 1, risk_band_id
ORDER BY risk_band_id;


-- ============================================================================
--  SECTION 10  |  QUALITY OF NEW BUSINESS
--  Answers: are the customers we are signing worth less than the ones we
--  used to sign? Logo growth can hide a fall in revenue per customer.
-- ============================================================================

SELECT '--- Quality of new business by signup cohort ---' AS section;

SELECT
    signup_cohort,
    COUNT(*)                                                AS new_customers,
    ROUND(AVG(mrr_at_signup))                               AS avg_mrr_per_customer,
    ROUND(AVG(seat_estimate), 1)                            AS avg_seats,
    ROUND(100.0 * COUNT(*) FILTER (WHERE plan_tier = 'Starter') / COUNT(*), 1)
                                                            AS starter_share_pct
FROM v_customers_clean
GROUP BY 1
ORDER BY 1;


SELECT '--- Early period vs late period: revenue per new customer ---' AS section;

SELECT
    CASE WHEN signup_cohort < DATE '2023-07-01' THEN 'H1 2023'
         WHEN signup_cohort >= DATE '2024-07-01' THEN 'H2 2024'
    END                                                     AS period,
    COUNT(*)                                                AS new_customers,
    ROUND(AVG(mrr_at_signup))                               AS avg_mrr_per_customer,
    ROUND(AVG(seat_estimate), 1)                            AS avg_seats
FROM v_customers_clean
WHERE signup_cohort < DATE '2023-07-01'
   OR signup_cohort >= DATE '2024-07-01'
GROUP BY 1
ORDER BY 1;
